version: "3.3"

services:
  postgres_323:
    container_name: postgres_323
    image: postgres:latest
    restart: always
    ports:
      - "5323:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_323:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      chmod +x /docker-entrypoint-initdb.d/*.sh;
      docker-entrypoint.sh postgres;
      "

  postgres_324:
    container_name: postgres_324
    image: postgres:latest
    restart: always
    ports:
      - "5324:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_324:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      chmod +x /docker-entrypoint-initdb.d/*.sh;
      docker-entrypoint.sh postgres;
      "

  postgres_422:
    container_name: postgres_422
    image: postgres:latest
    restart: always
    ports:
      - "5422:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_422:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      chmod +x /docker-entrypoint-initdb.d/*.sh;
      docker-entrypoint.sh postgres;
      "

  postgres_423:
    container_name: postgres_423
    image: postgres:latest
    restart: always
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_423:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      chmod +x /docker-entrypoint-initdb.d/*.sh;
      docker-entrypoint.sh postgres;
      "

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "3141:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_323
      - postgres_324
      - postgres_422
      - postgres_423

  postgres_gophertalk:
    image: postgres:latest
    container_name: postgres_gophertalk
    environment:
      POSTGRES_DB: ${POSTGRES_GOPHERTALK_DB}
      POSTGRES_USER: ${POSTGRES_GOPHERTALK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_GOPHERTALK_PASSWORD}
    ports:
      - "5391:5432"
    volumes:
      - postgres_gophertalk_data:/var/lib/postgresql/data

  postgres_gophertalk_migrate:
    image: migrate/migrate
    container_name: postgres_gophertalk_migrate
    environment:
      GOLANG_MIGRATE_POSTGRESQL_URL: ${GOLANG_MIGRATE_POSTGRESQL_URL}
    volumes:
      - gophertalk_backend_migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "${GOLANG_MIGRATE_POSTGRESQL_URL}",
        "up",
      ]
    depends_on:
      - postgres_gophertalk

  gophertalk_backend:
    build:
      context: https://github.com/shekshuev/gophertalk-backend.git#develop
    container_name: gophertalk_backend
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      ACCESS_TOKEN_EXPIRES: ${ACCESS_TOKEN_EXPIRES}
      REFRESH_TOKEN_EXPIRES: ${REFRESH_TOKEN_EXPIRES}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    volumes:
      - gophertalk_backend_migrations:/migrations
    ports:
      - "3000:3000"
    depends_on:
      - postgres_gophertalk_migrate

  gophertalk-frontend:
    build:
      context: https://github.com/shekshuev/gophertalk-frontend.git#main
      args:
        VITE_APP_API_URL: ${VITE_APP_API_URL}
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  postgres_ecampus:
    image: postgres:latest
    container_name: postgres_ecampus
    environment:
      POSTGRES_DB: ${POSTGRES_ECAMPUS_DB}
      POSTGRES_USER: ${POSTGRES_ECAMPUS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_GOPHERTALK_PASSWORD}
    ports:
      - "5392:5432"
    volumes:
      - postgres_ecampus_data:/var/lib/postgresql/data

  ecampus_app:
    build:
      context: https://github.com/shekshuev/ecampus.git#develop
      args:
        MIX_ENV: ${MIX_ENV}
    container_name: ecampus_app
    environment:
      POSTGRES_DB: ${POSTGRES_ECAMPUS_DB}
      POSTGRES_USER: ${POSTGRES_ECAMPUS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ECAMPUS_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_ECAMPUS_PORT}
      POSTGRES_HOSTNAME: ${POSTGRES_ECAMPUS_HOSTNAME}
      PHX_SERVER: ${PHX_SERVER}
      MIX_ENV: ${MIX_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "4000:4000"
    depends_on:
      - postgres_ecampus

volumes:
  postgres_data_323:
  postgres_data_324:
  postgres_data_422:
  postgres_data_423:
  pgadmin_data:
  postgres_gophertalk_data:
  gophertalk_backend_migrations:
  postgres_ecampus_data:
